### ISSUE TITLE
CMD close (issue found you can close ) 

### ISSUE THREAD

**Issue by papayou66** [Plasmatree/PID-Analyzer#1]
Hello the CMD close when i try to read a log 
Attached the log 
[1.zip](https://github.com/Plasmatree/PID-Analyzer/files/1311116/1.zip)

**Comment by Plasmatree** [comment]
Which system are you on? 

I got no problems with your log:
![0](https://user-images.githubusercontent.com/25606011/30560139-3f22d1c6-9cb7-11e7-9e00-32f165f56bbb.png)

**Comment by papayou66** [comment]
windows 10 64 b

**Comment by apeelme** [comment]
Me too...i use _example_smooth_tune.BBL_, w10 home 64bit.
![clipboard01](https://user-images.githubusercontent.com/868203/30561950-2281d8d6-9cbd-11e7-9b8c-999f6b9d0798.jpg)

**Comment by Plasmatree** [comment]
Ah, quite a hint! Thanks :)

**Comment by Plasmatree** [comment]
Seems like Windows sometimes returns the input path with or without quote marks. Maybe different language settings cause this.  

I added a check for quotemarks. 
New version is up!

**Comment by papayou66** [comment]
I found the issue !!! my bad:
You need to put the log in the same folder 
Know i need to learn how to use the diagram 
![zeus3](https://user-images.githubusercontent.com/19493158/30582454-07b32e80-9d24-11e7-9743-56ba6a50ef14.png)

**Comment by Plasmatree** [comment]
I'm not sure why your response for low input is below 1. Could be that it's caused by your deadband setting. I will have a look at it. 
What matters most is the shape. The actual hight is more comparable to stick sensitivity/rate (but not the same).

**Comment by Plasmatree** [comment]
@apeelme Have you tried again?

**Comment by apeelme** [comment]
@Plasmatree Thanks, working! ;)
