### ISSUE TITLE
Can't read logs with I/D set to zero

### ISSUE THREAD

**Issue by Legista** [Plasmatree/PID-Analyzer#17]
I'll be brief))
I started to tune quadcopter, set PIDs to 45/0/0 for both roll and pitch.
Now i faced this error - KeyError: 'axisD[0]'
Log attached.
Betaflight 3.3.2. It seems decoded csv (as bfl itself) does not contain fields for P,I,D if set them to zero.
[LOG00018.zip](https://github.com/Plasmatree/PID-Analyzer/files/2017813/LOG00018.zip)

**Comment by Plasmatree** [comment]
Will account for that case, thanks!

**Comment by Plasmatree** [comment]
Should be solved now.
