### ISSUE TITLE
cmd crashes

### ISSUE THREAD

**Issue by muhkuh0815** [Plasmatree/PID-Analyzer#2]
when i try with the "example_smooth_tune.BBL"  example file (or any of my own BBL files)
the pid-analyzer crashes while trying to generate the first .png file

Reading log 0...   Done!
Processing:
roll...   Done!
pitch...  Done!
yaw...  Done!

following files get created in the directory

example_smooth_tune_temp1.BBL gets created (2mb)
example_smooth_tune_temp1.01.csv gets created (15mb)
example_smooth_tune_temp1.01.event gets created (154 bytes)
example_smooth_tune_0.png gets created  ....  with a filesize of 0 

do i just need some sort of Plot/gnuplot for windows ? or do i have to ditch my windows 7 PC for a new one ...

ps: thanks for the nice work you done with this tool.

**Comment by Plasmatree** [comment]
It should be completely standalone. I guess I need to try it on win7. 
Thanks for the feedback!

**Comment by muhkuh0815** [comment]
thank you for looking into it.
![pidanalyze](https://user-images.githubusercontent.com/1222279/30589171-af6932f4-9d39-11e7-86a2-7c62417908ef.png)

**Comment by Plasmatree** [comment]
Reproduced it on Win7 and should be fixed now. 
New version is online!

Thanks for your feedback!

**Comment by muhkuh0815** [comment]
works like a charm now.
thanks for the great work!
