### ISSUE TITLE
Tight Layout error?

### ISSUE THREAD

**Issue by apeelme** [Plasmatree/PID-Analyzer#4]
When click _Tight layout_ button:
![log00001a_0](https://user-images.githubusercontent.com/868203/30659940-a8554ea6-9e3f-11e7-8a27-20fde8b979cd.png)
![clipboard02](https://user-images.githubusercontent.com/868203/30659870-721e0bd4-9e3f-11e7-8612-58d1d046f56a.jpg)

my log: 
[LOG00001.zip](https://github.com/Plasmatree/PID-Analyzer/files/1318745/LOG00001.zip)

**Comment by Plasmatree** [comment]
I guess it's caused by GridSpec which is used to arrange the plots. 
Is it crutial for you? It has nothing to do with the data, just with the plot arrangement within the window.

**Comment by apeelme** [comment]
I do not use, just tried it, and I wanted to help. ;)

**Comment by Plasmatree** [comment]
Thanks, I will keep it in mind!
