### ISSUE TITLE
[feature request] for setting "Optional plot name" via commandline

### ISSUE THREAD

**Issue by njdro** [Plasmatree/PID-Analyzer#52]
In addition to the `-l` or `--log`, please offer a `-n` or `--name` for specifying a plot name.  This would help from locating new files within the `./tmp` folder.

**Comment by mrRobot62** [comment]
Do I misunderstood your request?

Current version handle following arguments

$ >plasmatree
usage: PID-Analyzer.py [-h] [-l LOG] [-n NAME]
                       [--blackbox_decode BLACKBOX_DECODE] [-s SHOW]
                       [-nb NOISE_BOUNDS]
PID-Analyzer.py: error: argument -l/--log: expected one argument

**Comment by njdro** [comment]
Thank you! i had not seen those parameters listed. this helps very much
